
jobs:
  include:
    - os: linux
      dist: xenial
    #- os: linux
    #  dist: bionic
    #- os: linux
    #  dist: focal
    - stage: deploy
      script: skip
      before_install: []
      install: skip
      deploy:
        - provider: 'rubygems'
          on:
            branch: 'master'
            tags: true
          api_key:
            secure: "Crsrr71RwfGXjA2a32SLC8ADnf5yY61r78rUVA15RO2lfla/t0CA25rZ6WZD9b9m2kSasOSNxh2DCwNfZKjMuc9UCWxMZ0br0Pw4SIReka5RPMbxR+TeWNZ/B9xgb7z2V0KdtXtiYlIaV28YqkU1+Bm8qYC4cc8W/KtX7eji/94="
        - provider: 'rubygems'
          on:
            all_branches: true
            condition: '$TRAVIS_BRANCH =~ ^rc'
          api_key:
            secure: "Crsrr71RwfGXjA2a32SLC8ADnf5yY61r78rUVA15RO2lfla/t0CA25rZ6WZD9b9m2kSasOSNxh2DCwNfZKjMuc9UCWxMZ0br0Pw4SIReka5RPMbxR+TeWNZ/B9xgb7z2V0KdtXtiYlIaV28YqkU1+Bm8qYC4cc8W/KtX7eji/94="

language: ruby

rvm:
  - "2.6"
  - "2.7"
  - "2.5"

before_install:
  - sudo apt-get update -y
  - sudo apt-get install -qq pkg-config fuse libfuse-dev
  - sudo modprobe fuse
  - sudo chmod 666 /dev/fuse
  - sudo chown root:$USER /etc/fuse.conf
  - yes | gem update --system -N --force
  - gem install bundler

script:
  - bundle exec rake

cache:
  bundler: true
