
sudo: required
dist: trusty
language: ruby

rvm:
  - "2.4"
  - "2.5"
  - "2.6"
  - "2.7"

before_install:
  - sudo apt-get update -y
  - sudo apt-get install -qq pkg-config fuse libfuse-dev
  - sudo modprobe fuse
  - sudo chmod 666 /dev/fuse
  - sudo chown root:$USER /etc/fuse.conf
  - yes | gem update --system -N --force
  - gem install bundler

script:
  - bundle exec rake

cache:
  bundler: true
