
sudo: required

jobs:
  include:
    - os: linux
      dist: xenial
    - os: linux
      dist: bionic
    - os: linux
      dist: focal
    - os: linux
      dist: trusty

language: ruby

rvm:
  - "2.6"
  - "2.7"
  - "2.5"
  - "2.4"

before_install:
  - sudo apt-get update -y
  - sudo apt-get install -qq pkg-config fuse libfuse-dev
  - sudo modprobe fuse
  - sudo chmod 666 /dev/fuse
  - sudo chown root:$USER /etc/fuse.conf
  - yes | gem update --system -N --force
  - gem install bundler

script:
  - bundle exec rake

cache:
  bundler: true
